apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-function
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-function
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/fklein82/Inclusion-nodeportal.git
      ref:
        branch: main
